package com.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", schema = "public")
public class Account implements java.io.Serializable {

	private int accountİd;
	private Customer customer;
	private String accountCurrency;
	private String accountType;
	private Long balance;

	public Account() {
	}

	public Account(int accountİd, String accountCurrency, String accountType) {
		this.accountİd = accountİd;
		this.accountCurrency = accountCurrency;
		this.accountType = accountType;
	}

	public Account(int accountİd, Customer customer, String accountCurrency, String accountType, Long balance) {
		this.accountİd = accountİd;
		this.customer = customer;
		this.accountCurrency = accountCurrency;
		this.accountType = accountType;
		this.balance = balance;
	}

	@Id

	@Column(name = "account_id", unique = true, nullable = false)
	public int getAccountİd() {
		return this.accountİd;
	}

	public void setAccountİd(int accountİd) {
		this.accountİd = accountİd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "account_currency", nullable = false, length = 10)
	public String getAccountCurrency() {
		return this.accountCurrency;
	}

	public void setAccountCurrency(String accountCurrency) {
		this.accountCurrency = accountCurrency;
	}

	@Column(name = "account_type", nullable = false, length = 50)
	public String getAccountType() {
		return this.accountType;
	}

	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	@Column(name = "balance")
	public Long getBalance() {
		return this.balance;
	}

	public void setBalance(Long balance) {
		this.balance = balance;
	}

}
