package com.model;

// default package
// Generated 19 Eki 2023 11:36:35 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", schema = "public")
public class Address implements java.io.Serializable {

	private int addressİd;
	private Customer customer;
	private String adressType;
	private String streetAddress;
	private String city;
	private String state;
	private String postalCode;

	public Address() {
	}

	public Address(int addressİd, String streetAddress, String city, String postalCode) {
		this.addressİd = addressİd;
		this.streetAddress = streetAddress;
		this.city = city;
		this.postalCode = postalCode;
	}

	public Address(int addressİd, Customer customer, String adressType, String streetAddress, String city, String state,
			String postalCode) {
		this.addressİd = addressİd;
		this.customer = customer;
		this.adressType = adressType;
		this.streetAddress = streetAddress;
		this.city = city;
		this.state = state;
		this.postalCode = postalCode;
	}

	@Id

	@Column(name = "address_id", unique = true, nullable = false)
	public int getAddressİd() {
		return this.addressİd;
	}

	public void setAddressİd(int addressİd) {
		this.addressİd = addressİd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "adress_type", length = 10)
	public String getAdressType() {
		return this.adressType;
	}

	public void setAdressType(String adressType) {
		this.adressType = adressType;
	}

	@Column(name = "street_address", nullable = false)
	public String getStreetAddress() {
		return this.streetAddress;
	}

	public void setStreetAddress(String streetAddress) {
		this.streetAddress = streetAddress;
	}

	@Column(name = "city", nullable = false, length = 100)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", length = 50)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "postal_code", nullable = false, length = 20)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

}
