package com.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * CommandExecuter generated by hbm2java
 */
@Entity
@Table(name = "command_executer", schema = "public")
public class CommandExecuter implements java.io.Serializable {

	private int commandİd;
	private String commandName;
	private String className;
	private String method;

	public CommandExecuter() {
	}

	public CommandExecuter(int commandİd, String commandName, String className, String method) {
		this.commandİd = commandİd;
		this.commandName = commandName;
		this.className = className;
		this.method = method;
	}

	@Id

	@Column(name = "command_id", unique = true, nullable = false)
	public int getCommandİd() {
		return this.commandİd;
	}

	public void setCommandİd(int commandİd) {
		this.commandİd = commandİd;
	}

	@Column(name = "command_name", nullable = false)
	public String getCommandName() {
		return this.commandName;
	}

	public void setCommandName(String commandName) {
		this.commandName = commandName;
	}

	@Column(name = "class_name", nullable = false)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@Column(name = "method", nullable = false)
	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

}
