package com.model;

// default package
// Generated 19 Eki 2023 11:36:35 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", schema = "public")
public class Customer implements java.io.Serializable {

	private int customerİd;
	private Long pidNo;
	private Long taxNo;
	private String firstName;
	private String lastName;
	private String gender;
	private Date birthDate;
	private boolean status;
	private Set<Account> accounts = new HashSet<Account>(0);
	private Set<Address> addresses = new HashSet<Address>(0);
	private Set<Phone> phones = new HashSet<Phone>(0);

	public Customer() {
	}

	public Customer(int customerİd, String firstName, String lastName, String gender, Date birthDate, boolean status) {
		this.customerİd = customerİd;
		this.firstName = firstName;
		this.lastName = lastName;
		this.gender = gender;
		this.birthDate = birthDate;
		this.status = status;
	}

	public Customer(int customerİd, Long pidNo, Long taxNo, String firstName, String lastName, String gender,
			Date birthDate, boolean status, Set<Account> accounts, Set<Address> addresses, Set<Phone> phones) {
		this.customerİd = customerİd;
		this.pidNo = pidNo;
		this.taxNo = taxNo;
		this.firstName = firstName;
		this.lastName = lastName;
		this.gender = gender;
		this.birthDate = birthDate;
		this.status = status;
		this.accounts = accounts;
		this.addresses = addresses;
		this.phones = phones;
	}

	@Id

	@Column(name = "customer_id", unique = true, nullable = false)
	public int getCustomerİd() {
		return this.customerİd;
	}

	public void setCustomerİd(int customerİd) {
		this.customerİd = customerİd;
	}

	@Column(name = "pid_no")
	public Long getPidNo() {
		return this.pidNo;
	}

	public void setPidNo(Long pidNo) {
		this.pidNo = pidNo;
	}

	@Column(name = "tax_no")
	public Long getTaxNo() {
		return this.taxNo;
	}

	public void setTaxNo(Long taxNo) {
		this.taxNo = taxNo;
	}

	@Column(name = "first_name", nullable = false, length = 50)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", nullable = false, length = 50)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "gender", nullable = false, length = 1)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birth_date", nullable = false, length = 13)
	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Account> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set<Account> accounts) {
		this.accounts = accounts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Phone> getPhones() {
		return this.phones;
	}

	public void setPhones(Set<Phone> phones) {
		this.phones = phones;
	}

}
