package com.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Phone generated by hbm2java
 */
@Entity
@Table(name = "phone", schema = "public")
public class Phone implements java.io.Serializable {

	private int phoneİd;
	private Customer customer;
	private String phoneType;
	private String phoneNumber;

	public Phone() {
	}

	public Phone(int phoneİd, String phoneNumber) {
		this.phoneİd = phoneİd;
		this.phoneNumber = phoneNumber;
	}

	public Phone(int phoneİd, Customer customer, String phoneType, String phoneNumber) {
		this.phoneİd = phoneİd;
		this.customer = customer;
		this.phoneType = phoneType;
		this.phoneNumber = phoneNumber;
	}

	@Id

	@Column(name = "phone_id", unique = true, nullable = false)
	public int getPhoneİd() {
		return this.phoneİd;
	}

	public void setPhoneİd(int phoneİd) {
		this.phoneİd = phoneİd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "phone_type", length = 10)
	public String getPhoneType() {
		return this.phoneType;
	}

	public void setPhoneType(String phoneType) {
		this.phoneType = phoneType;
	}

	@Column(name = "phone_number", nullable = false, length = 20)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

}
